name: Deploy to file share

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  DeployFiles:
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Pull Repo
        run: 'u:'
        run: cd actions_test\Git_Actions
        run: git pull origin main
        shell: cmd