name: Deploy to file share

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  DeployFiles:
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Deploy files
        run: git clone https://github.com/ImRyanFromIT/Git_Actions u:\actions_test\git_actions
        shell: cmd