name: Deploy to file share

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  DeployFiles:
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Pull Repo
        run: | 
        u:
        cd actions_test\Git_Actions
        git pull origin main
        shell: cmd